// <auto-generated />
using Coursera.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coursera.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230321190759_StudentMigration")]
    partial class StudentMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Coursera.Models.StudentsET", b =>
                {
                    b.Property<int>("Studentid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Studentid"));

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentAge")
                        .HasColumnType("int");

                    b.Property<string>("StudentEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentFirstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentLastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentPhone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Studentid");

                    b.ToTable("StudentsET");

                    b.HasData(
                        new
                        {
                            Studentid = 1,
                            Gender = "Male",
                            Password = "01227007298",
                            StudentAge = 21,
                            StudentEmail = "mahmoudmatar49@gmail.com",
                            StudentFirstname = "mahmoud",
                            StudentLastname = "Matar",
                            StudentPhone = "01128673348"
                        },
                        new
                        {
                            Studentid = 2,
                            Gender = "Male",
                            Password = "01111614941",
                            StudentAge = 20,
                            StudentEmail = "Ziad12@yahoo.com",
                            StudentFirstname = "Ziad",
                            StudentLastname = "ElSadany",
                            StudentPhone = "01003246344"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
